
version: 2

sources:
  - name: erp
    description: Source from Discorama sales database.
    schema: dbt_sales_erp_discorama
    tables:
      
      - name: staff
        description: Table of information about staffs.
        columns:
          - name: staff_id
            description: It is a primary key to staffs table.
            tests:
              - unique
              - not_null

      - name: customer
        description: Table of information about customers.
        columns:
          - name: customer_id
            description: It is a primary key to curtomers table.
            tests:
              - unique
              - not_null

      - name: address
        description: Table of information about address.
        columns:
          - name: address_id
            description: It is a primary key to address table.
            tests:
              - unique
              - not_null   

      - name: city
        description: Table of information about city.
        columns:
          - name: city_id
            description: It is a primary key to city table.
            tests:
              - unique
              - not_null       
                      
      - name: country
        description: Table of information about country.
        columns:
          - name: country_id
            description: It is a primary key to country table.
            tests:
              - unique
              - not_null

      - name: film
        description: Table of information about film.
        columns:
          - name: film_id
            description: It is a primary key to film table.
            tests:
              - unique
              - not_null

      - name: inventory
        description: Table of information about inventory.
        columns:
          - name: inventory_id
            description: It is a primary key to inventory table.
            tests:
              - unique
              - not_null

      - name: film_category
        description: Table about which category that film represent.
        columns:
          - name: film_id
            description: It is a primary key to film_category table.
            tests:
              - unique
              - not_null

      - name: category
        description: Table of information about category.
        columns:
          - name: category_id
            description: It is a primary key to category table.
            tests:
              - unique
              - not_null

      - name: film_actor
        description: Table of information about which film that actor participeted.
        columns:
          - name: film_id
            description: This is a identification code for films.
            tests:              
              - not_null
          
          - name: actor_id
            description: This is a identification code for actors.
            tests:              
              - not_null

      - name: actor
        description: Table of information about actors.
        columns:
          - name: actor_id
            description: It is a primary key to actor table.
            tests:
              - unique
              - not_null

      - name: rental
        description: Table of information about rental date and inventories.
        columns:
          - name: rental_id
            description: It is a primary key to rental table.
            tests:
              - unique
              - not_null

      - name: payment
        description: Table of information about payments rental.
        columns:
          - name: payment_id
            description: It is a primary key to payment table.
            tests:
              - unique
              - not_null                            